In [3]:
import tensorflow as tf

In [4]:
print(tf.__version__)

2.12.0


In [5]:
scalar = tf.constant(5)
print(scalar.ndim) # 0 dimensional

vector = tf.constant([1,2,3,4,5,6])
print(vector.ndim) # 1 dimensional

matrix = tf.constant([[1.,2.56,3.],[4,5.6,6]])
print(matrix.ndim) # 2 dimensional

tensor = tf.constant([[[1,2], [3,4]], [[5,6], [7,8]]])
print(tensor.ndim) # 3 dimensional

0
1
2
3


In [9]:
changable = tf.Variable([10, 7])
not_changable = tf.constant([10, 7])

changable, not_changable

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [11]:
changable[0].assign(6) # we can do so, but not on 'not_changable'
changable

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([6, 7], dtype=int32)>

In [25]:
test = tf.random.Generator.from_seed([5,4,6])
test = test.normal(shape=(6,2))

test2 = tf.random.Generator.from_seed([5,4,6])
test2 = test2.normal(shape=(6,2))

test == test2 # because we had the same seed, they are equal

test = tf.random.Generator.from_seed(3)
test2 = tf.random.Generator.from_seed(3)

test.normal(shape=(2,3)) == test2.normal(shape=(2,3)) # because we had the same seed, they are equal

<tf.Tensor: shape=(2, 3), dtype=bool, numpy=
array([[ True,  True,  True],
       [ True,  True,  True]])>

In [36]:
tensor = tf.constant([[1, 2], [3, 4], [5, 6]])
tensor = tf.random.shuffle(tensor) # items in the array are shuffled, but the inner-arrays stay the same
tensor

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)>